### ISSUE TITLE
Feature Request:  Splash Screen Image

### ISSUE THREAD

**Issue by RodneyBaker** [motionmonster/motionmonster#31]
It would be great to be able to have a (custom) image (or short sequence of images) run when Motion Monster launches.

Some considerations:
- Most users just want the program to launch and they want it to launch quickly so... an option should be available to bypass the splash screen (or 'silently load')

- Some programs have a splash screen but keep the image close-hold because it's a brand for the software.  That image is then replace annually or upon major updates.

- I use one program that has a method to load a bitmap and a mask in place of the default splash screen.  few people know about the filename required but for those that know... they can personalize the software to launch an image of their choosing at startup

- A still image splash is nice... one with transparency mask nicer... customizable image better... a short animation potentially awesome as it would sell the brand 'MotionMonster'.  Two methods might be used to animate the image:
- Use of a file format that animates (gif, mov or avi)
- Use of a single image that pans/scrolls ala spritesheet
- Use of a sequence of images properly named/numbered
- Optional ability to display splash as sequence in order linearly, ping pong, ramp up/down, random, etc would be a crazy thing to waste programming time on...........

Concerns (Con/Pro):
Loading time can already be too long <> The splash image give user something to look at while loading 
If splash screen is bypassed or customizable the brand can get diluted <> users like customizability and they love seeing their images
Users might file bug reports/trouble tickets if their image doesn't display <> user forum can easily handle these issues

Selling point for Turtletooth:  ;)
An image from each of the students involved in a project (or a short animation produced by them) can display every time they open the software.  While overkill and very likely not appropriate for splash screen purposes this might in a way serve the purpose of viewing 'Dailies'.  Every time Motion Monster is launched it might display the current status (ala thumbnail showing) of the projects current progress.   Yeah... that's a bit too much but I thought I'd run with the idea...

Disclaimer:  This request is mainly a means for me to be able to post something to say "Thanks!" for all you do and continue to do in the OpenToonz community.   I envy your students!

**Comment by turtletooth** [comment]
Thanks for the suggestion, but right now, I think I'm going to leave the splash screen for now.  I do need to work on the small icon though.  Thanks for all the help finding bugs and issues with the software.
