### ISSUE TITLE
Question:  Camera Capture Overlay - Sizing Image to Camera

### ISSUE THREAD

**Issue by RodneyBaker** [motionmonster/motionmonster#46]
I should know this but...

What is the easiest way to size images in the xsheet to that of the camera?
I get an error message when trying to load an overlay that states the images needs to match the size of the camera.

I have a feeling I may find the answer to this as soon as I submit...

EDIT:
I now see this isn't the original problem I mistakenly thought the error was because the image and OpenToonz camera weren't the same size but this is referring to the video camera.   The underlying issue right now is that Motion Monster isn't recognizing my video camera so I can't adjust the resolution setting.   That should be easy enough to address.

Sorry for the distraction.  
I think this can be closed.

**Comment by turtletooth** [comment]
Thanks Rodney- I will post the update soon.
