### ISSUE TITLE
Camera Capture:  Dropdown not available to select camera

### ISSUE THREAD

**Issue by RodneyBaker** [motionmonster/motionmonster#47]
I believe this was reported for the portable but I'd have to check to see if a fix was ever released.
It operates as expected in official OpenToonz v1.1.1 release.

When opening a Camera Capture dialog the camera field is very tiny and when selecting the arrow only three dots (...) appear.   Perhaps this relates to a possible typo in the code or simply a field area that is too narrow?

Here's a view of what I'm seeing:
![cannot select camera](https://cloud.githubusercontent.com/assets/2576432/18214649/a5d03dee-7113-11e6-8745-1a57e319e988.png)

**Comment by turtletooth** [comment]
Thanks Rodney.

I have a fix for that already.  I will try and post a new version tonight (that will also include audio recording)

**Comment by turtletooth** [comment]
This should be fixed in the new release - let me know please.

**Comment by RodneyBaker** [comment]
I'm getting an error (error 123) during  install that is preventing me from checking out the latest release.
The error I get is attached.

![error123](https://cloud.githubusercontent.com/assets/2576432/18341253/c8657e78-756e-11e6-80af-7e4825d8e1aa.png)

I get this even if I rename the stuff folder.

I'll double check to see if it is something on my end and download the installer again in case it is corrupted.

**Comment by turtletooth** [comment]
Sorry about that- my installer gets caught on the Japanese and Chinese characters in the config folder.  Fixed now.

**Comment by RodneyBaker** [comment]
Back up and running with the newest release... (thanks for that!) and the fix is in for this issue (#47).
I can now see and select a camera.

I am having some issues with crashing with the camera capture feature but those (and a few others) have already been reported in the OpenToonz master branch.  I may need to individually specify them because they were part of the larger collection (most of which have been implemented).

Thanks Jeremy!

![47 selecting camera - resolved](https://cloud.githubusercontent.com/assets/2576432/18363851/7e82d2a2-75d1-11e6-9f41-5cf49c5d50c1.png)
!

**Comment by turtletooth** [comment]
Thanks
